import test from 'node:test';
import assert from 'node:assert/strict';
import {SearchBudgetOrchestrator,searchStages,stageFloors} from '../application/search-budget-orchestrator.js';
import {ConnectionProviderSession} from '../journey/connection/provider-session.js';
import {ConnectionBudget} from '../journey/connection/budget.js';
import {connectionDiagnostics} from '../journey/connection/types.js';
import {ConnectionSearchEngine} from '../journey/connection/connection-search-engine.js';
import {searchModeConfig} from '../application/search-mode.js';
import {classifySearchCompletion} from '../application/search-completion.js';
import {SearchDiagnosticObserver,buildSearchDebug} from '../application/search-debug-diagnostics.js';
import {availabilityFailure,normalizeAvailability} from '../providers/railkit/railkit-normalizers.js';
import type {RailwayProvider} from '../providers/railway-provider.js';
import type {TrainCandidate} from '../domain/types/train-search.js';
import type {TravelClass} from '../journey/types/journey-segment.js';
const request={fromStationCode:'A',toStationCode:'D',journeyDate:'20-09-2099',classes:['3A','SL','2A','1A','3E','2S','CC','EC'] as TravelClass[],quota:'GN' as const};
const availabilityRequest={...request,trainNumber:'10000',travelClass:'3A'};
function fixture({strong=false,deferred=false,multiUsable=true}={}){
 const calls:{train:string;coach:string}[]=[];
 const t=(trainNumber:string,fromStationCode:string,toStationCode:string,departureTime:string,arrivalTime:string,durationMinutes:number):TrainCandidate=>({trainNumber,trainName:'Synthetic',fromStationCode,toStationCode,departureTime,arrivalTime,durationMinutes});
 const seeds=[t('10000','A','D','20:00','10:00',840),t('10001','A','D','20:00','10:00',840)];
 const legs=[t('20001','A','B','20:00','23:00',180),t('20002','B','C','01:00','05:00',240),t('20003','C','D','07:00','10:00',180),t('20004','A','C','20:00','05:00',540),t('20005','B','D','01:00','10:00',540)];
 const provider:RailwayProvider={
 async searchTrainsBetweenStations(r){return {provider:'fake',providerState:'SUCCESS',trains:[...seeds,...legs].filter(t=>t.fromStationCode===r.fromStationCode&&t.toStationCode===r.toStationCode)};},
 async getTrainInfo(n){return {trainNumber:n,trainName:'Synthetic',sourceStationCode:'A',sourceStationName:'A',destinationStationCode:'D',destinationStationName:'D',sourceDepartureTime:'20:00',destinationArrivalTime:'10:00',route:['A','B','C','D'].map((stationCode,i)=>({stationCode,stationName:stationCode,distanceKm:[0,100,850,1000][i],dayNumber:i?2:1,departureTime:['20:00','01:00','07:00','10:00'][i],arrivalTime:['20:00','23:00','05:00','10:00'][i],haltMinutes:5}))};},
 async getAvailability(r){calls.push({train:r.trainNumber,coach:r.travelClass});const full=r.fromStationCode==='A'&&r.toStationCode==='D';const available=(strong&&full)||(deferred&&full&&r.travelClass==='1A')||(multiUsable&&['20001','20002','20003'].includes(r.trainNumber));return {provider:'railkit',providerState:'SUCCESS',request:r,days:[{date:r.journeyDate,state:available?'AVAILABLE':'WAITLIST'}]};}
 };return {provider,calls,run:()=>new ConnectionSearchEngine(provider).search(request,searchModeConfig('DEEP'))};
}
for(const mode of ['QUICK','STANDARD','DEEP'] as const)test(`${mode} floors fit unchanged global limits`,()=>{const limit=searchModeConfig(mode).budget!.maxAvailabilityCalls!;assert.ok(Object.values(stageFloors[mode]).reduce((a,b)=>a+b,0)<=limit);if(mode==='DEEP')assert.equal(limit,40);});
test('earlier stages cannot consume protected multi floor',()=>{const o=new SearchBudgetOrchestrator(40,'DEEP');o.releaseStageProtection('direct');o.releaseStageProtection('sameTrainRecovery');while(o.canSpend('oneChange',1))o.recordSpend('oneChange');assert.equal(o.remaining(),8);assert.equal(o.canSpend('multiInterchange',3,true),true);assert.ok(o.preventedByReservation>0);});
test('unused stage floor released into shared pool',()=>{const o=new SearchBudgetOrchestrator(40,'DEEP');const before=o.protectedFor('direct');o.releaseStageProtection('multiInterchange',false);assert.equal(o.protectedFor('direct'),before-8);assert.equal(o.stageUsage.multiInterchange.state,'NOT_APPLICABLE');});
test('atomic two-edge validation waits rather than spending protected capacity',()=>{const o=new SearchBudgetOrchestrator(40,'DEEP');for(let i=0;i<31;i++)o.recordSpend('direct');assert.equal(o.canSpend('oneChange',2,true),false);assert.equal(o.preventedByAtomicCost,1);assert.equal(o.insufficientRemainingBudget,false);});
test('three uncached segments cannot begin with two globally remaining',()=>{const o=new SearchBudgetOrchestrator(40,'DEEP');for(let i=0;i<38;i++)o.recordSpend('direct');assert.equal(o.canSpend('multiInterchange',3,true),false);assert.equal(o.insufficientRemainingBudget,true);});
test('cache-aware cost and stage accounting remain exact',async()=>{const f=fixture();const o=new SearchBudgetOrchestrator(40,'DEEP');const s=new ConnectionProviderSession(f.provider,new ConnectionBudget({maxAvailabilityCalls:40}),connectionDiagnostics(),3,o);await s.availability(availabilityRequest,true);await s.availability({...availabilityRequest,toStationCode:'B'},true);const queries=[availabilityRequest,{...availabilityRequest,toStationCode:'B'},{...availabilityRequest,toStationCode:'C'}];assert.equal(s.estimatedUncachedAvailabilityCost(queries),1);assert.equal(s.canValidate('multiInterchange',queries),true);const before=f.calls.length;for(const q of queries)await s.availability(q,false,{directLimit:0,stationLimit:0,multiLimit:40});assert.equal(f.calls.length-before,1);assert.equal(o.stageUsage.multiInterchange.cacheHits,2);assert.equal(Object.values(o.stageUsage).reduce((n,s)=>n+s.externalAvailabilityCalls,0),s.diagnostics.availabilityCalls);});
test('key live shape: two trains eight classes and recovery do not starve multi',async()=>{const f=fixture();const r=await f.run();assert.equal(r.multi?.diagnostics.multiInterchangeActivated,true);assert.ok(r.multi!.diagnostics.multiInterchangePartialPathsGenerated>0);assert.ok(r.multi!.diagnostics.multiInterchangeAvailabilityChecks>0);assert.ok(r.multi!.candidates.length>0);assert.ok(f.calls.length<=40);const o=r.diagnostics.budgetOrchestration!;assert.ok(o.stageUsage.direct.initialClassChecks<=4);assert.ok(o.stageUsage.direct.deferredClassChecks>=12);assert.equal(o.stageUsage.multiInterchange.meaningfulAttempt,true);assert.equal(Object.values(o.stageUsage).reduce((n,s)=>n+s.externalAvailabilityCalls,0),r.diagnostics.availabilityCalls);});
test('deferred direct classes remain reachable after fallback opportunities',async()=>{const f=fixture({deferred:true,multiUsable:false});const r=await f.run();assert.ok(f.calls.some(c=>c.train==='10000'&&c.coach==='1A'));assert.ok(r.results.some(r=>r.type==='DIRECT'&&r.segments[0].travelClass==='1A'));assert.ok(r.diagnostics.budgetOrchestration!.stageUsage.direct.resumedClassChecks>0);});
test('strong earlier result never forces protected capacity expenditure',async()=>{const f=fixture({strong:true});const r=await new ConnectionSearchEngine(f.provider).search({...request,classes:['3A']},searchModeConfig('STANDARD'));assert.equal(r.multi?.diagnostics.multiInterchangeAvailabilityChecks,0);assert.equal(r.diagnostics.budgetOrchestration?.protectedRemainingForLaterStages,0);assert.ok(f.calls.length<30);});
test('generation alone never marks meaningful attempt',()=>{const o=new SearchBudgetOrchestrator(40,'DEEP');o.start('multiInterchange');o.releaseStageProtection('multiInterchange');assert.equal(o.stageUsage.multiInterchange.meaningfulAttempt,false);});
test('floor pause alone never makes whole search partial',()=>{const o=new SearchBudgetOrchestrator(40,'DEEP');for(let i=0;i<32;i++)o.recordSpend('direct');o.canSpend('oneChange',2,true);assert.deepEqual(classifySearchCompletion({...connectionDiagnostics(),budgetOrchestration:o.snapshot()}),{searchCompleted:true,partialResults:false});});
test('true exhaustion and atomic insufficiency have distinct completion',()=>{for(const flag of ['availabilityBudgetExhausted','insufficientRemainingBudgetForNextExpansion'] as const){const d={...connectionDiagnostics(),[flag]:true};assert.equal(classifySearchCompletion(d).partialResults,true);const debug=buildSearchDebug({results:[],diagnostics:d},new SearchDiagnosticObserver(),searchModeConfig('DEEP'),0,{availability:flag==='availabilityBudgetExhausted'?40:38,discovery:0,trainInfo:0});assert.equal(debug.completionReason,flag==='availabilityBudgetExhausted'?'GLOBAL_AVAILABILITY_BUDGET':'INSUFFICIENT_REMAINING_BUDGET');}});
for(const [error,expected] of [[new Error('generic provider failure'),false],[new Error('rate limit maybe'),false],[{status:429},true],[{response:{status:429}},true]] as const)test(`provider category ${JSON.stringify(error)} rate=${expected}`,()=>{const result=availabilityFailure(availabilityRequest,error);const o=new SearchDiagnosticObserver();o.observeAvailability(availabilityRequest,result);const debug=buildSearchDebug({results:[],diagnostics:{...connectionDiagnostics(),providerErrorCount:1,availabilityBudgetExhausted:true}},o,searchModeConfig('DEEP'),0,{availability:40,discovery:0,trainInfo:0});assert.equal(debug.failureReasons.includes('PROVIDER_LIMITED'),expected);assert.equal(debug.primaryFailureReason,expected?'PROVIDER_LIMITED':'SEARCH_BUDGET_EXHAUSTED');});
test('known booking rejection and invalid response classified without rate-limit inference',()=>{const result=normalizeAvailability({success:false,error:'Sorry, this train is not available for booking for this date'},availabilityRequest);const o=new SearchDiagnosticObserver();o.observeAvailability(availabilityRequest,result);o.observeAvailability(availabilityRequest,normalizeAvailability({},availabilityRequest));assert.equal(o.providerFailures.BOOKING_UNSUPPORTED,1);assert.equal(o.providerFailures.INVALID_PROVIDER_RESPONSE,1);assert.equal(o.providerFailures.RATE_LIMITED,0);});
test('recovery cannot cross the one-change and multi protection boundary',()=>{const o=new SearchBudgetOrchestrator(40,'DEEP');o.releaseStageProtection('direct');while(o.canSpend('sameTrainRecovery',1))o.recordSpend('sameTrainRecovery');assert.equal(o.remaining(),16);assert.equal(o.canSpend('oneChange',2,true),true);});
test('adaptive accounting and cache hits are separate and deterministic',()=>{const o=new SearchBudgetOrchestrator(40,'DEEP');o.releaseStageProtection('multiInterchange');for(let i=0;i<7;i++)o.recordSpend('direct');o.recordCacheHit('direct');const s=o.snapshot();assert.equal(s.stageUsage.direct.adaptiveCallsBorrowed,3);assert.equal(s.adaptivePoolUsed,3);assert.equal(s.globalAvailabilityUsed,7);assert.equal(s.stageUsage.direct.cacheHits,1);});
test('atomic cost includes existing per-station validation ceiling',async()=>{const f=fixture();const o=new SearchBudgetOrchestrator(40,'DEEP');const s=new ConnectionProviderSession(f.provider,new ConnectionBudget({maxAvailabilityCalls:40}),connectionDiagnostics(),3,o);assert.equal(s.canValidate('oneChange',[availabilityRequest,{...availabilityRequest,toStationCode:'B'}],0,1),false);assert.equal(f.calls.length,0);assert.equal(o.insufficientRemainingBudget,false);});
test('local availability budget remains forty despite protected reservations',async()=>{const f=fixture({multiUsable:false});const r=await f.run();assert.equal(r.diagnostics.budgetOrchestration!.globalAvailabilityLimit,40);assert.ok(r.diagnostics.availabilityCalls<=40);assert.ok(r.diagnostics.trainDiscoveryCalls<=10);assert.ok(r.diagnostics.trainInfoCalls<=10);});
