import test from 'node:test';
import assert from 'node:assert/strict';
import { multiInterchangeSearch } from '../application/multi-interchange-planner.js';
import { JourneySearchService } from '../application/journey-search-service.js';
import { multiModes, multiDiagnostics, type PartialJourneyPath } from '../domain/planner/types.js';
import { bestPossibleScore, pathScore, pathDominates, retainBeam, shouldRunMultiInterchangeSearch } from '../domain/planner/ranking.js';
import { ConnectionBudget } from '../journey/connection/budget.js';
import { ConnectionProviderSession } from '../journey/connection/provider-session.js';
import { connectionDiagnostics } from '../journey/connection/types.js';
import { connectionTimes, scheduledRun } from '../journey/connection/timing.js';
import type { RailwayProvider } from '../providers/railway-provider.js';
import type { TrainCandidate } from '../domain/types/train-search.js';
import type { TravelClass } from '../journey/types/journey-segment.js';
import { rankPublicJourneys, serializeMulti } from '../application/multi-serialization.js';
const request={fromStationCode:'A',toStationCode:'D',journeyDate:'20-09-2099',classes:['3A','SL','2A'] as TravelClass[],quota:'GN' as const};
const seed:TrainCandidate={trainNumber:'10000',trainName:'Corridor',fromStationCode:'A',toStationCode:'D',departureTime:'08:00',arrivalTime:'20:00',durationMinutes:720};
function setup({mixed=false,firstBad=false,secondBad=false,double=false,detour=false,fail=false,rac=false}={}) {
 const calls={discovery:0,info:0,availability:0};const seats:string[]=[];
 const legs:TrainCandidate[]=[
 {trainNumber:'10001',trainName:'One',fromStationCode:'A',toStationCode:'B',departureTime:'20:00',arrivalTime:'23:00',durationMinutes:180,distanceKm:detour?2000:100,availableClasses:mixed?['3A']:undefined},
 {trainNumber:'10002',trainName:'Two',fromStationCode:'B',toStationCode:'C',departureTime:firstBad?'23:30':'01:00',arrivalTime:double?'23:00':'05:00',durationMinutes:firstBad?330:double?1320:240,distanceKm:100,availableClasses:mixed?['SL']:undefined},
 {trainNumber:'10003',trainName:'Three',fromStationCode:'C',toStationCode:'D',departureTime:secondBad?'05:30':double?'01:00':'07:00',arrivalTime:double?'04:00':'10:00',durationMinutes:secondBad?270:180,distanceKm:100,availableClasses:mixed?['2A']:undefined},
 ];
 const provider:RailwayProvider={
 async searchTrainsBetweenStations(r){calls.discovery++;if(fail&&r.fromStationCode==='A'&&r.toStationCode==='C')throw new Error('private');return {provider:'fake',providerState:'SUCCESS',trains:r.fromStationCode==='A'&&r.toStationCode==='D'?[seed]:legs.filter(t=>t.fromStationCode===r.fromStationCode&&t.toStationCode===r.toStationCode)};},
 async getTrainInfo(n){calls.info++;return {trainNumber:n,trainName:'Corridor',sourceStationCode:'A',sourceStationName:'A',destinationStationCode:'D',destinationStationName:'D',sourceDepartureTime:'08:00',destinationArrivalTime:'20:00',route:['A','B','C','D'].map((stationCode,i)=>({stationCode,stationName:stationCode,distanceKm:i*100,dayNumber:1,arrivalTime:`${8+i*3}:00`.padStart(5,'0'),departureTime:`${8+i*3}:05`.padStart(5,'0'),haltMinutes:5}))};},
 async getAvailability(r){calls.availability++;seats.push(`${r.trainNumber}:${r.journeyDate}:${r.travelClass}`);return {provider:'railkit',providerState:'SUCCESS',request:r,days:[{date:r.journeyDate,state:r.trainNumber==='10000'?'WAITLIST':rac?'RAC':'AVAILABLE'}],fare:{totalFare:500,currency:'INR'}};}
 };
 const session=new ConnectionProviderSession(provider,new ConnectionBudget({maxAvailabilityCalls:40,maxTrainDiscoveryCalls:20,maxTrainInfoCalls:10}),connectionDiagnostics(),3);
 return {calls,seats,legs,provider,session,run:()=>multiInterchangeSearch(request,[seed],session,multiModes.DEEP,connectionTimes())};
}
test('three-train construction and invariants',async()=>{const f=setup();const r=await f.run();const c=r.candidates[0];assert.ok(c);assert.equal(c.segments.length,3);assert.equal(c.trainChangeCount,2);assert.equal(c.reservedCoverage.ratio,1);assert.equal(c.segments[0].from.code,'A');assert.equal(c.segments[2].to.code,'D');assert.equal(c.totalReservedFare,1500);for(let i=1;i<3;i++){assert.equal(c.segments[i-1].to.code,c.segments[i].from.code);assert.ok(c.connections[i-1].minutes>=60);}assert.ok(c.warnings.includes('MULTIPLE_TRAIN_CHANGES'));assert.equal(r.diagnostics.multiInterchangeStrongStopCount,1);});
test('mixed classes without cartesian expansion',async()=>{const f=setup({mixed:true});const r=await f.run();assert.deepEqual(r.candidates[0].segments.map(s=>s.classCode),['3A','SL','2A']);assert.equal(r.candidates[0].classChangeCount,2);assert.equal(f.calls.availability,3);});
for(const double of [false,true])test(`boarding dates ${double?'two':'one'} midnight rollover`,async()=>{const c=(await setup({double}).run()).candidates[0];assert.deepEqual(c.segments.map(s=>s.journeyDate),['20-09-2099','21-09-2099',double?'22-09-2099':'21-09-2099']);});
for(const field of ['firstBad','secondBad'] as const)test(`${field} pruned before seats`,async()=>{const f=setup({[field]:true});const r=await f.run();assert.equal(r.candidates.length,0);assert.equal(f.calls.availability,0);assert.ok(r.diagnostics.multiInterchangeTimingPruned>0);});
test('detour rejected before availability',async()=>{const f=setup({detour:true});const r=await f.run();assert.equal(f.calls.availability,0);assert.ok(r.diagnostics.multiInterchangeDetourPruned>0);});
test('bottleneck checks last edge first on equal class counts',async()=>{const f=setup();await f.run();assert.ok(f.seats[0].startsWith('10003:'));});
test('cached availability pays zero again',async()=>{const f=setup();await f.run();const n=f.calls.availability;const r=await f.run();assert.equal(f.calls.availability,n);assert.ok(r.diagnostics.multiInterchangeCacheHits>=3);});
for(const mode of ['QUICK','STANDARD','DEEP'] as const)test(`${mode} phase call ceilings`,async()=>{const f=setup();await multiInterchangeSearch(request,[seed],f.session,multiModes[mode],connectionTimes());assert.ok(f.calls.discovery<=multiModes[mode].discovery);assert.ok(f.calls.info<=multiModes[mode].trainInfo);assert.ok(f.calls.availability<=multiModes[mode].availability);});
test('global remaining budgets cap phases',async()=>{const f=setup();f.session.budget.used.availability=39;f.session.budget.used.discovery=19;const r=await f.run();assert.ok(f.calls.availability<=1);assert.ok(f.calls.discovery<=1);assert.equal(r.candidates.length,0);});
test('RAC stays usable and emits warning',async()=>{const r=await setup({rac:true}).run();assert.ok(r.candidates[0].warnings.includes('RAC_NOT_CONFIRMED_BERTH'));assert.equal(r.diagnostics.multiInterchangeStrongStopCount,0);});
test('strong direct and strong one-change skip STANDARD',()=>{for(const type of ['DIRECT','DIFFERENT_TRAIN_CONNECTION'] as const){const r={type,segments:[{availabilityState:'AVAILABLE'}],connectionSafety:'GOOD'} as never;assert.equal(shouldRunMultiInterchangeSearch([r],[],false),false);assert.equal(shouldRunMultiInterchangeSearch([r],[],true),true);}});
test('weak RAC results activate planner',()=>assert.equal(shouldRunMultiInterchangeSearch([{type:'DIRECT',segments:[{availabilityState:'RAC'}]} as never],[]),true));
function path(i=0):PartialJourneyPath {const f=setup();return {runs:[scheduledRun({...f.legs[0],trainNumber:String(10001+i)},request.journeyDate)!],visitedStations:new Set(['A','B']),visitedTrains:new Set(['10001']),progress:.3,score:100-i,distance:100};}
test('50 frontier candidates retain bounded diverse beam',()=>{const d=multiDiagnostics();const beam=retainBeam(Array.from({length:50},(_,i)=>({...path(i),visitedTrains:new Set([String(i)])})),5,d);assert.equal(beam.length,5);assert.equal(d.multiInterchangeMaxFrontier,5);assert.equal(d.multiInterchangeBeamPruned,45);});
test('dominance only in matching temporal/resource context',()=>{const a=path(),b=path();b.score--;assert.equal(pathDominates(a,b),true);b.runs=[{...b.runs[0],arrival:b.runs[0].arrival+5}];assert.equal(pathDominates(a,b),false);});
test('optimistic upper bound exceeds realized score',async()=>{const c=(await setup().run()).candidates[0];assert.ok(bestPossibleScore(path())>=pathScore(c,request.classes));const p=path();p.runs[0].arrival+=100000;assert.ok(bestPossibleScore(p)<1230);});
test('public serialization excludes score and raw fields',async()=>{const c=(await setup().run()).candidates[0];Object.assign(c,{secret:'raw'});const raw=JSON.stringify(serializeMulti(c));assert.ok(!raw.includes('score'));assert.ok(!raw.includes('secret'));});
test('cross-type tradeoffs deterministic without dropping recovery',async()=>{const m=serializeMulti((await setup().run()).candidates[0]);const r={type:'JOURNEY_RECOVERY',reservedCoverage:{ratio:.92},segments:[{type:'RESERVED_TRAIN',availability:'AVAILABLE'}],selfManagedSegmentCount:1} as never;assert.equal(rankPublicJourneys([m,r]).length,2);assert.deepEqual(rankPublicJourneys([m,r]),rankPublicJourneys([m,r]));});
test('full service constructs 8B when direct and one-change fail',async()=>{const f=setup();const result=await new JourneySearchService(f.provider,{logger:()=>{}}).search({from:'A',to:'D',date:request.journeyDate,classes:['3A'],searchMode:'DEEP'});assert.ok(result.results.some(r=>r.type==='MULTI_TRAIN_JOURNEY'));assert.equal(result.meta.apiUsage?.externalCalls,f.calls.discovery+f.calls.info+f.calls.availability);});
test('same operational train reuse is loop-pruned',async()=>{const f=setup();f.legs[2].trainNumber=f.legs[1].trainNumber;const r=await f.run();assert.equal(r.candidates.length,0);assert.ok(r.diagnostics.multiInterchangeLoopPruned>0);assert.equal(f.calls.availability,0);});
test('repeated station corridor cannot seed cyclic planner',async()=>{const f=setup();const original=f.provider.getTrainInfo;f.provider.getTrainInfo=async n=>{const info=await original(n);info.route[2].stationCode='A';return info;};const r=await f.run();assert.equal(r.candidates.length,0);assert.equal(f.calls.availability,0);});
test('upper-bound pruning avoids seat calls for inferior tight branch',async()=>{const f=setup({rac:true});f.legs.push({...f.legs[2],trainNumber:'10004',departureTime:'06:00',arrivalTime:'09:00'});const r=await multiInterchangeSearch({...request,classes:['3A']},[seed],f.session,multiModes.DEEP,connectionTimes());assert.ok(r.candidates.length>0);assert.ok(r.diagnostics.multiInterchangeUpperBoundPruned>0);assert.ok(!f.seats.some(s=>s.startsWith('10004:')));});
test('one controlled availability failure permits class fallback',async()=>{const f=setup();const original=f.provider.getAvailability;let once=true;f.provider.getAvailability=async r=>{if(once){once=false;throw new Error('controlled fake failure');}return original(r);};const r=await f.run();assert.ok(r.candidates.length);assert.equal(f.session.diagnostics.providerErrorCount,1);});
test('invalid fractional call budget rejects',async()=>{const f=setup();await assert.rejects(multiInterchangeSearch(request,[seed],f.session,{...multiModes.STANDARD,availability:1.5},connectionTimes()));});
test('RAC retains preferred class when no AVAILABLE upgrade exists',async()=>{const c=(await setup({rac:true}).run()).candidates[0];assert.deepEqual(c.segments.map(s=>s.classCode),['3A','3A','3A']);});
test('high branching discovery cannot exceed provider or frontier caps',async()=>{const f=setup({rac:true});const original=f.provider.searchTrainsBetweenStations;f.provider.searchTrainsBetweenStations=async r=>{const result=await original(r);return {...result,trains:result.trains.flatMap(t=>Array.from({length:50},(_,i)=>({...t,trainNumber:String(Number(t.trainNumber)+i*10)})))};};const r=await f.run();assert.ok(f.calls.discovery<=multiModes.DEEP.discovery);assert.ok(f.calls.info<=multiModes.DEEP.trainInfo);assert.ok(f.calls.availability<=multiModes.DEEP.availability);assert.ok(r.diagnostics.multiInterchangeMaxFrontier<=multiModes.DEEP.beamWidth);});
