import type { Fare } from '../../../domain/types/fare.js';
import type { TravelClass } from '../../types/journey-segment.js';
import type { InventoryCheck } from '../types.js';
export interface RecoveryInput { trainNumber: string; fromStation: string; toStation: string; boardingDateTime: string; arrivalDateTime: string; distanceKm: number; requestedClasses: string[]; quota?: 'GN'; supportedClasses?: readonly string[] }
export interface RecoveryLimits { minimumReservedCoverageRatio: number; maxSplitPoints: number; maxIntervals: number; maxStatesPerNode: number; maxResults: number }
export const defaultRecoveryLimits: Readonly<RecoveryLimits> = Object.freeze({minimumReservedCoverageRatio:.50,maxSplitPoints:8,maxIntervals:24,maxStatesPerNode:64,maxResults:5});
export interface ReservationEvidence { fromStation: string; toStation: string; departureDateTime: string; arrivalDateTime: string; boardingDate: string; distanceKm: number; availabilityStatus:'AVAILABLE'|'RAC'; availabilityText?:string; fare?:Fare }
export interface ReservedSegment { type:'RESERVED'; trainNumber:string; fromStation:string; toStation:string; departureDateTime:string; arrivalDateTime:string; selectedClass:TravelClass; quota:'GN'; availabilityStatus:'AVAILABLE'|'RAC'; availabilityText?:string; distanceKm:number; fare?:Fare; reservationParts:ReservationEvidence[] }
export interface SelfManagedSegment { type:'SELF_MANAGED'; fromStation:string; toStation:string; distanceKm:number; notice:string }
export type RecoverySegment=ReservedSegment|SelfManagedSegment;
export type RecoveryStatus='FULL_RESERVED_SINGLE_CLASS'|'FULL_RESERVED_SPLIT_CLASS'|'PARTIAL_RESERVED_RECOVERY'|'NO_USABLE_RECOVERY'|'INVENTORY_CHECK_INCOMPLETE';
export interface RecoverySolution { trainNumber:string; requestedFrom:string; requestedTo:string; requestedDistanceKm:number; recoveryStatus:RecoveryStatus; segments:RecoverySegment[]; reservedDistanceKm:number; selfManagedDistanceKm:number; reservedCoverageRatio:number; reservedSegmentCount:number; classChanges:number; trainChanges:0; availableSegmentCount:number; racSegmentCount:number; waitlistChecks:number; totalKnownFare:number; fareComplete:boolean; availabilityRequestsUsed:number; cacheHits:number }
export interface RecoveryDiagnostics { progressive?: {stationsEligible:number;stationsConsidered:number;stationsRemaining:number;stationRoundsAttempted:number;complete:boolean}; trainStopsConsidered:number; candidateIntervalsGenerated:number; intervalsPruned:number; splitPointsConsidered:number; splitPointsByTier:Record<'MAJOR'|'MEDIUM'|'SMALL',number>; availabilityRequestsUsed:number; availabilityCacheHits:number; budgetRemaining:number; intervalsAvailable:number; intervalsRac:number; intervalsWaitlist:number; providerErrors:number; fullCoverageSolutions:number; partialCoverageSolutions:number; bestReservedCoverageRatio:number; bestClassChanges:number; selfManagedDistanceKm:number; searchRoundsAttempted:string[]; truncated:boolean; truncationReasons:string[]; atomicIntervalDeferrals:number; missingDistanceStopsSkipped:number; statesPruned:number; minimumReservedCoverageRatio:number }
export interface RecoveryResult { best:RecoverySolution; solutions:RecoverySolution[]; diagnostics:RecoveryDiagnostics; checks:{fromStation:string;toStation:string;boardingDate:string;check:InventoryCheck}[] }
